/* Auto-generated by genmsg_cpp for file /home/ros/dev/rosbook/chapter7_tutorials/msg/Move.msg */
#ifndef CHAPTER7_TUTORIALS_MESSAGE_MOVE_H
#define CHAPTER7_TUTORIALS_MESSAGE_MOVE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace chapter7_tutorials
{
template <class ContainerAllocator>
struct Move_ {
  typedef Move_<ContainerAllocator> Type;

  Move_()
  : M(0)
  {
  }

  Move_(const ContainerAllocator& _alloc)
  : M(0)
  {
  }

  typedef int32_t _M_type;
  int32_t M;


  typedef boost::shared_ptr< ::chapter7_tutorials::Move_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chapter7_tutorials::Move_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Move
typedef  ::chapter7_tutorials::Move_<std::allocator<void> > Move;

typedef boost::shared_ptr< ::chapter7_tutorials::Move> MovePtr;
typedef boost::shared_ptr< ::chapter7_tutorials::Move const> MoveConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::chapter7_tutorials::Move_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::chapter7_tutorials::Move_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace chapter7_tutorials

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::chapter7_tutorials::Move_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::chapter7_tutorials::Move_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::chapter7_tutorials::Move_<ContainerAllocator> > {
  static const char* value() 
  {
    return "edde3fa002e91a032c7588d79d5320d3";
  }

  static const char* value(const  ::chapter7_tutorials::Move_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xedde3fa002e91a03ULL;
  static const uint64_t static_value2 = 0x2c7588d79d5320d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::chapter7_tutorials::Move_<ContainerAllocator> > {
  static const char* value() 
  {
    return "chapter7_tutorials/Move";
  }

  static const char* value(const  ::chapter7_tutorials::Move_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::chapter7_tutorials::Move_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 M\n\
\n\
";
  }

  static const char* value(const  ::chapter7_tutorials::Move_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::chapter7_tutorials::Move_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::chapter7_tutorials::Move_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.M);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Move_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chapter7_tutorials::Move_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::chapter7_tutorials::Move_<ContainerAllocator> & v) 
  {
    s << indent << "M: ";
    Printer<int32_t>::stream(s, indent + "  ", v.M);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CHAPTER7_TUTORIALS_MESSAGE_MOVE_H

