/* Auto-generated by genmsg_cpp for file /home/ros/dev/rosbook/chapter7_tutorials/msg/Vector3.msg */
#ifndef CHAPTER7_TUTORIALS_MESSAGE_VECTOR3_H
#define CHAPTER7_TUTORIALS_MESSAGE_VECTOR3_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace chapter7_tutorials
{
template <class ContainerAllocator>
struct Vector3_ {
  typedef Vector3_<ContainerAllocator> Type;

  Vector3_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  Vector3_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;


  typedef boost::shared_ptr< ::chapter7_tutorials::Vector3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chapter7_tutorials::Vector3_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Vector3
typedef  ::chapter7_tutorials::Vector3_<std::allocator<void> > Vector3;

typedef boost::shared_ptr< ::chapter7_tutorials::Vector3> Vector3Ptr;
typedef boost::shared_ptr< ::chapter7_tutorials::Vector3 const> Vector3ConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::chapter7_tutorials::Vector3_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::chapter7_tutorials::Vector3_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace chapter7_tutorials

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::chapter7_tutorials::Vector3_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::chapter7_tutorials::Vector3_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::chapter7_tutorials::Vector3_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const  ::chapter7_tutorials::Vector3_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::chapter7_tutorials::Vector3_<ContainerAllocator> > {
  static const char* value() 
  {
    return "chapter7_tutorials/Vector3";
  }

  static const char* value(const  ::chapter7_tutorials::Vector3_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::chapter7_tutorials::Vector3_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::chapter7_tutorials::Vector3_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::chapter7_tutorials::Vector3_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::chapter7_tutorials::Vector3_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Vector3_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chapter7_tutorials::Vector3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::chapter7_tutorials::Vector3_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CHAPTER7_TUTORIALS_MESSAGE_VECTOR3_H

